PATDOC:
  entity: application
  pk: SDOBI/B200/B210/DNUM
  fields:
    SDOBI/B500/B570/B577: num_claims
    SDOBI/B500/B540/STEXT: title

    SDOCL/CL/CLM:
      entity: claim
      fields:
        # the asterisk specifies that all sub-elements of each PATDOC/SDOCL/CL/CLM
        #  will be reduced to their text content, and the results of each such
        #  reduction (for each PATDOC/SDOCL/CL/CLM element, should there be more
        #  than one) will be concatenated together with the `joiner` string -- in
        #  this case, a newline.
        "*":
          fieldname: claim_text
          joiner: "\n"

    SDOBI/B100/B110/DNUM: doc_number
    SDOBI/B100/B130: kind_code
    SDOBI/B100/B190: country_code

    SDOBI/B300:
      entity: foreign_filing
      fields:
        B310/DNUM: doc_number
        B320/DATE: date
        B330/CTRY: country_code

    SDOBI/B200/B220/DATE: filing_date
    SDOBI/B100/B140/DATE: doc_date
    SDOBI/B500/B510/B511: IPC_primary
    SDOBI/B500/B510/B512:
      fieldname: IPC_secondary
      joiner: "|"

    SDOBI/B500/B520/B521: USPC-primary
    SDOBI/B500/B520/B522:
      fieldname: USPC_secondary
      joiner: "|"
    SDOBI/B500/B520/B522US: USPC_secondary

    SDOBI/B500/B510/B516: IPC_edition

    SDOBI/B700/B720/B721:
      entity: applicant
      fields:
        PARTY-US/NAM/SNM/STEXT: last_name
        PARTY-US/NAM/FNM: given_name
        PARTY-US/NAM/ONM/STEXT: org_name
        PARTY-US/ADR/CITY: res_city
        PARTY-US/ADR/CTRY: res_country

    SDOBI/B200/B210/DNUM: app_number
    SDOBI/B200/B211US: series_code

    SDOBI/B700/B730:
      entity: assignee
      fields:
        B731/PARTY-US/NAM/ONM/STEXT: org_name
        B732US: role

    SDOBI/B500/B560/B561:
      entity: citation
      fields:
        PCIT/DOC/DNUM: doc_number
        PCIT/DOC/KIND: kind_code
        PCIT/DOC/CTRY: country_code
        PCIT/PARTY-US/NAM/SNM/STEXT: name
        PCIT/DOC/DATE: date
        CITED-BY-EXAMINER: cited_by:examiner
        CITED-BY-OTHER: cited_by:other
        PCIT/PNC: cited_in

    SDOBI/B500/B560/B562:
      entity: citation
      fields:
        CITED-BY-EXAMINER: cited_by:examiner
        CITED-BY-OTHER: cited_by:other
        NCIT/STEXT: cited_in_other

    SDOBI/B700/B745/B746/PARTY-US/NAM/SNM/STEXT: examiner1_last_name
    SDOBI/B700/B745/B746/PARTY-US/NAM/FNM: examiner1_given_name
    SDOBI/B700/B745/B748US: examiner1_dep
    SDOBI/B700/B745/B747/PARTY-US/NAM/SNM/STEXT: examiner2_last_name
    SDOBI/B700/B745/B747/PARTY-US/NAM/FNM: examiner2_first_name

    SDOBI/B600/B620:
      entity: divided_application
      fields:
        PARENT-US/PDOC/DOC/DNUM: doc_number
        PARENT-US/PDOC/DOC/DATE: date
        PARENT-US/PDOC/DOC/KIND: kind_code
        PARENT-US/PDOC/DOC/CTRY: country_code

    SDOBI/B600/B630/B631:
      entity: continued_application
      fields:
        PARENT-US/PDOC/DOC/DNUM: doc_number
        PARENT-US/PDOC/DOC/DATE: date
        PARENT-US/PDOC/DOC/KIND: kind_code
        PARENT-US/PDOC/DOC/CTRY: country_code

    SDOBI/B600/B680US:
      entity: provisional_application
      fields:
        DOC/DNUM: doc_number
        DOC/DATE: date
