us-patent-grant:
  <entity>: patent
  <primary_key>: us-bibliographic-data-grant/publication-reference/document-id/doc-number
  <filename_field>: source_file
  <fields>:
    us-bibliographic-data-grant/number-of-claims: num_claims

    claims/claim:
      <entity>: claim
      <fields>:
        # the asterisk specifies that all sub-elements of each us-patent-grant/claims/claim
        #  will be reduced to their text content, and the results of each such
        #  reduction (for each us-patent-grant/claims/claim element, should there be more
        #  than one) will be concatenated together with the `joiner` string -- in
        #  this case, a newline.
        "*":
          <fieldname>: claim_text
          <joiner>: "\n"

    us-bibliographic-data-grant/invention-title: title

    us-bibliographic-data-grant/publication-reference/document-id/doc-number: doc_number
    us-bibliographic-data-grant/publication-reference/document-id/kind: kind_code
    us-bibliographic-data-grant/publication-reference/document-id/country: country_code

    us-bibliographic-data-grant/priority-claims/priority-claim:
      <entity>: foreign_filing
      <fields>:
        doc-number: doc_number
        country: country_code
        date: date

    us-bibliographic-data-grant/application-reference/document-id/date: filing_date
    us-bibliographic-data-grant/publication-reference/document-id/date: doc_date


    us-bibliographic-data-grant/classifications-ipcr/classification-ipcr/section:
        <fieldname>: IPC_section
        <joiner>: "|"
    us-bibliographic-data-grant/classifications-ipcr/classification-ipcr/class:
        <fieldname>: IPC_class
        <joiner>: "|"
    us-bibliographic-data-grant/classifications-ipcr/classification-ipcr/subclass:
        <fieldname>: IPC_subclass
        <joiner>: "|"
    us-bibliographic-data-grant/classifications-ipcr/classification-ipcr/main-group:
        <fieldname>: IPC_main_group
        <joiner>: "|"
    us-bibliographic-data-grant/classifications-ipcr/classification-ipcr/subgroup:
        <fieldname>: IPC_subgroup
        <joiner>: "|"
    us-bibliographic-data-grant/classifications-ipcr/classification-ipcr/ipc-version-indicator/date:
        <fieldname>: IPC_edition
        <joiner>: "|"


    us-bibliographic-data-grant/classification-national/country : USPC_country
    us-bibliographic-data-grant/classification-national/edition : USPC_edition
    us-bibliographic-data-grant/classification-national/main-classification : USPC_primary
    us-bibliographic-data-grant/classification-national/further-classification :
      <fieldname>: USPC_secondary
      <joiner>: "|"


    us-bibliographic-data-grant/parties/applicants/applicant/addressbook:
      <entity>: applicant
      <fields>:
        last-name: last_name
        first-name: given_name
        orgname: org_name
        address/city: res_city
        address/country: res_country

    us-bibliographic-data-grant/application-reference/document-id/doc-number: app_number
    us-bibliographic-data-grant/us-application-series-code: series_code

    #Note: this is pulling an attribute, and may not be the final syntax for that
    us-bibliographic-data-grant/application-reference/@appl-type: filing_type

    us-bibliographic-data-grant/assignees/assignee:
      <entity>: assignee
      <fields>:
        addressbook/orgname: org_name
        addressbook/address/street: street
        addressbook/address/city: city
        addressbook/address/county: county
        addressbook/address/state: state
        addressbook/address/country: country
        addressbook/address/postcode: postal_code
        addressbook/role: role


    us-bibliographic-data-grant/references-cited/citation:
      <entity>: citation
      <fields>:
        patcit/document-id/country: country_code
        patcit/document-id/doc-number: doc_number
        patcit/document-id/kind: kind_code
        patcit/document-id/name: name
        patcit/document-id/date: date
        category:
          <fieldname>: cited_by
          <enum_map>:
            cited by examiner: examiner
            cited by other: other
        classification-national/country: class_country
        classification-national/main-classification: class_main
        nplcit/othercit: cited_in_other #I think this is the analogous field

    us-bibliographic-data-grant/examiners/primary-examiner/last-name: examiner1_last_name
    us-bibliographic-data-grant/examiners/primary-examiner/first-name: examiner1_given_name
    us-bibliographic-data-grant/examiners/primary-examiner/department: examiner1_dep

    us-bibliographic-data-grant/examiners/assistant-examiner/last-name: examiner2_last_name
    us-bibliographic-data-grant/examiners/assistant-examiner/first-name: examiner2_first_name

    # Related Documents
    ## Parent Applications
    us-bibliographic-data-grant/us-related-documents/addition/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: addition
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/division/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: divisional
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/continuation/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: continuation
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/continuation-in-part/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: continuation_in_part
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/continuing-reissue/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: continuing_reissue
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/reissue/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: reissue
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/us-divisional-reissue/us-relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: divisional_reissue
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/reexamination/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: reexamination
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/us-reexamination-reissue-merger/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: reexamination_reissue_merger
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/substitution/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: substitution
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/us-provisional-application:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: us_provisional_application
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date
        us-provisional-application-status: status

    us-bibliographic-data-grant/us-related-documents/utility-model-basis/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: utility_model_basis
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/related-publication/relation/parent-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: related_publication
          - <fieldname>: relationship
            <enum_type>: parent
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date


    ##Child documents
    us-bibliographic-data-grant/us-related-documents/addition/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: addition
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/division/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: divisional
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/continuation/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: continuation
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/continuation-in-part/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: continuation_in_part
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/continuing-reissue/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: continuing_reissue
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/reissue/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: reissue
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/us-divisional-reissue/us-relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: divisional_reissue
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/reexamination/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: reexamination
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/us-reexamination-reissue-merger/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: reexamination_reissue_merger
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/substitution/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: substitution
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/utility-model-basis/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: utility_model_basis
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/related-publication/relation/child-doc:
      <entity>: related_document
      <fields>:
        document-id:
          - <fieldname>: type
            <enum_type>: related_publication
          - <fieldname>: relationship
            <enum_type>: child
        document-id/country: country_code
        document-id/doc-number: doc_number
        document-id/date: date

    us-bibliographic-data-grant/us-related-documents/correction:
      <entity>: correction
      <fields>:
        document-corrected/document-id/doc-number: corrected_doc
        type-of-correction: correction_type
        gazette-reference: gazette_reference
        text: correction_text
